export const conversations = [
  {
    id: '1',
    name: 'Blue Note Club',
    message: "We'd love to have you perform next Friday!",
    time: '2:30 PM',
    unread: true,
    img: 'https://randomuser.me/api/portraits/women/33.jpg',
    online: true,
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    message: 'Looking forward to our collaboration',
    time: '10:15 AM',
    unread: false,
    img: 'https://randomuser.me/api/portraits/women/32.jpg',
    online: true,
  },
  {
    id: '3',
    name: 'Jazz Festival Organizer',
    message: 'Can you send your technical requirements?',
    time: 'Yesterday',
    unread: true,
    img: 'https://randomuser.me/api/portraits/women/34.jpg',
    online: true,
  },
  {
    id: '4',
    name: 'Mike from The Band Next Door',
    message: 'Great meeting you yesterday at the venue',
    time: 'Yesterday',
    unread: false,
    img: 'https://randomuser.me/api/portraits/women/35.jpg',
    online: true,
  },
  {
    id: '5',
    name: 'Armando Ferry',
    message: 'Can i check that?',
    time: '09:34 PM',
    img: 'https://placehold.co/50x50/png?text=AF',
    online: false,
    unread: false,
  },
  {
    id: '6',
    name: 'Annette Fritsch',
    message: 'Thanks!',
    time: '09:34 PM',
    img: 'https://placehold.co/50x50/png?text=AFR',
    online: true,
    unread: false,
  },
];
